name: Weather Check

on:
  schedule:
    - cron: "0 10 * * *"  # Runs daily at 10 AM UTC (adjust if needed)
  workflow_dispatch:  # Allow manual trigger

jobs:
  check-weather:
    runs-on: ubuntu-latest

    env:
      OWM_API_KEY: ${{ secrets.OWM_API_KEY }}
      LATITUDE: ${{ secrets.LATITUDE }}
      LONGITUDE: ${{ secrets.LONGITUDE }}
      TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
      TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install requests

      - name: Run weather check
        run: python .weather-check/weather_check.py
